### ISSUE TITLE
Mapnik 3 support

### ISSUE THREAD

**Issue by alculquicondor** [springmeyer/nik2img#2]
This is the error I'm getting on mapnik 3:
```
Traceback (most recent call last):
  File "/usr/local/bin/nik2img.py", line 238, in <module>
    main()
  File "/usr/local/bin/nik2img.py", line 228, in main
    nik_map = ComposeDebug(mapfile,**options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/mapnik_utils/composer.py", line 263, in __init__
    Compose.__init__(self,mapfile,**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mapnik_utils/composer.py", line 67, in __init__
    self.prepare()
  File "/usr/local/lib/python2.7/dist-packages/mapnik_utils/composer.py", line 271, in prepare
    super(ComposeDebug,self).prepare()
  File "/usr/local/lib/python2.7/dist-packages/mapnik_utils/composer.py", line 81, in prepare
    self.register_fonts()
  File "/usr/local/lib/python2.7/dist-packages/mapnik_utils/composer.py", line 335, in register_fonts
    super(ComposeDebug,self).register_fonts()
  File "/usr/local/lib/python2.7/dist-packages/mapnik_utils/composer.py", line 100, in register_fonts
    self.font_handler = FontHandler()
  File "/usr/local/lib/python2.7/dist-packages/mapnik_utils/fonts.py", line 12, in __init__
    self.fontdir = mapnik.fontscollectionpath
  File "/usr/local/lib/python2.7/dist-packages/mapnik_utils/version_adapter.py", line 66, in __getattr__
    return getattr(self.__instance, attr)
AttributeError: 'module' object has no attribute 'fontscollectionpath'
```
Are there any plans for supporting it?

**Comment by alculquicondor** [comment]
Using master version, I get this:
```
Traceback (most recent call last):
  File "/usr/local/bin/nik2img.py", line 230, in <module>
    main()
  File "/usr/local/bin/nik2img.py", line 220, in main
    nik_map = ComposeDebug(mapfile,**options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/mapnik_utils/composer.py", line 260, in __init__
    Compose.__init__(self,mapfile,**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mapnik_utils/composer.py", line 64, in __init__
    self.prepare()
  File "/usr/local/lib/python2.7/dist-packages/mapnik_utils/composer.py", line 268, in prepare
    super(ComposeDebug,self).prepare()
  File "/usr/local/lib/python2.7/dist-packages/mapnik_utils/composer.py", line 78, in prepare
    self.register_fonts()
  File "/usr/local/lib/python2.7/dist-packages/mapnik_utils/composer.py", line 332, in register_fonts
    super(ComposeDebug,self).register_fonts()
  File "/usr/local/lib/python2.7/dist-packages/mapnik_utils/composer.py", line 97, in register_fonts
    self.font_handler = FontHandler()
  File "/usr/local/lib/python2.7/dist-packages/mapnik_utils/fonts.py", line 10, in __init__
    self.fontdir = mapnik.fontscollectionpath
AttributeError: 'module' object has no attribute 'fontscollectionpath'
```

**Comment by alculquicondor** [comment]
Hello @springmeyer are there any plans for publishing a build of this on pypi?

**Comment by springmeyer** [comment]
@alculquicondor no, I am not actively developing or supporting this tool.
